config/routes.rb
Rails.application.routes.draw do
  root 'home#show'

  patch "profile", to: "profile#update", as: :profile

  # Feature flipping
  post   'features/enable/:feature',  to: "features#create",  as: :enable
  delete 'features/disable/:feature', to: "features#destroy", as: :disable

  # The demo pages which use feature toggles to unlock the next step...
  post 'demo/reset'
  get 'demo/start'
  get 'demo/actor'
  get 'demo/group', as: :coffee_beta
  get 'demo/percentage'

  # The example pages
  get 'example/index', as: :examples
  get 'example/:slug', to: "example#show", as: :example

  get "cli", to: "cli#show", as: :cli
  post "cli", to: "cli#execute"

  get 'connect/:token', to: "cloud#connect", as: :cloud_connect

  # The Flipper UI gem interface.
  #
  # IMPORTANT: In production, you'd want to limit access to this, or anybody would be able to
  #   control your feature toggles.
  #
  # More info on Flipper UI Security & Authorization:
  #   https://www.flippercloud.io/docs/ui#security
  mount Flipper::UI.app(Flipper) => '/flipper'
end

app/models/example.rb
class Example
  attr_accessor :title, :desc, :icon, :custom_flag, :tags

  def self.list
    [
      new(
        title: "Circuit Breakers",
        desc: "A quick way to temporarily enable or disable a single service for everyone or only affected users when that service isn't performing at 100%.",
        icon: "cpu",
        custom_flag: :search,
        tags: [[:permanent, :success], [:internal, :secondary]]
      ),
      new(
        title: "Backup Providers",
        desc: "A quick way to instantly toggle all connected systems from one provider to another in the case of downtime or degraded performance from a primary provider.",
        icon: "arrow-left-right",
        custom_flag: :email_backup,
        tags: [[:permanent, :success], [:internal, :secondary]]
      ),
      new(
        title: "Managing External Tools",
        desc: "Provide toggles to developers so they can enable or disable functionality like development tools, support system widgets, or other tools that aren't always needed in every environment.",
        icon: "wrench-adjustable",
        custom_flag: :profiler,
        tags: [[:permanent, :success], [:internal, :secondary]]
      ),
      new(
        title: "Incremental Feature Releases",
        desc: "An example of gradually expanding the audience for a given feature in order to find problems before releasing it to more people.",
        icon: "circle-half",
        custom_flag: :reporting,
        tags: [[:temporary, :info], [:external, :warning]]
      )
    ]
  end

  def initialize(title:, desc:, icon:, custom_flag: nil, tags: [])
    @title = title
    @desc = desc
    @icon = icon
    @custom_flag = custom_flag
    @tags = tags
  end

  def flag
    (custom_flag || partial).to_sym
  end

  def slug
    title.downcase.parameterize
  end

  def exists?
    File.exist?(example_file)
  end

  def partial
    title.downcase.parameterize(separator: '_')
  end

  def to_partial_path
    "example/#{partial}"
  end

  private

  def example_file
    Rails.root.join("app/views/example/_#{partial}.html.erb")
  end
end

app/controllers/example_controller.rb
class ExampleController < ApplicationController
  def index
  end

  def show
    @example = Example.list.select { |ex| ex.slug == params[:slug] }.first
    @feature = Flipper.feature(@example.flag)
  end
end

app/helpers/example_helper.rb
module ExampleHelper
end

app/views/example/_backup_providers.html.erb
<%= uses([
  [
    "cloud-slash-fill",
    "<strong>Reduce the impact of provider downtime</strong> by being able to instantly switch backend providers from one to the other and back again without re-deploying."
  ],
  [
    "cloud-lightning-rain-fill",
    "<strong>Instantly balance traffic to multiple providers if one is experiencing degraded performance</strong> to balance your reliance on any single provider."
  ],
  [
    "pie-chart-fill",
    "<strong>Split traffic between multiple providers</strong> to mitigate the potential impact of one provider going offline and ensuring you aren't entirely reliant on your primary provider."
  ],
  [
    "person-raised-hand",
    "<strong>Reduce support requests</strong> by insulating your customers from downtime caused by a single external vendor."
  ],
]) %>

<%
  total_users = User.count

  # Only paying customers can make beverage selections, so that's a good proxy
  #   for paid/VIPs
  paid = User.where(beverage: %i[water tea coffee]).count
%>

<% content_for :aside do %>
  <div class="card border-5 border-dark rounded-4">
    <div class="card-header p-3 pb-2 border-bottom">
      <%= flag_status(@example.flag) %>
    </div>
    <div class="card-body p-5">
      <% if @feature.on? %>
        <%# 100% to backup %>
        <div class="container text-center">
          <div class="row align-items-end">
            <div class="col flex-column align-items-center align-content-end justify-content-end">
              <div class="text-bg-danger rounded-pill d-inline-flex align-items-center align-content-center justify-content-center gap-2 px-4 py-3">
                <%= icon 'hdd-rack', 'bi-medium' %>
                <small>Primary</small>
                <span class="badge bg-light rounded-pill text-danger">Offline</span>
              </div>
            </div>
            <div class="col flex-column align-items-center">
              <div class="bg-dark rounded-pill d-inline-flex align-items-center align-content-center justify-content-center text-white gap-1 ps-2 pe-1 py-1">
                <%= icon 'people-fill', 'bi-medium' %>
                <small>All</small>
                <span class="badge bg-light rounded-pill text-dark"><%= total_users %></span>
              </div>
              <div class="w-100"><%= icon 'arrow-down-circle-fill', 'bi-medium text-secondary my-3' %></div>
              <div class="bg-success rounded-pill d-inline-flex align-items-center align-content-center justify-content-center text-white gap-2 px-4 py-3">
                <%= icon 'hdd-rack-fill', 'bi-medium' %>
                <small>Backup</small>
                <span class="badge bg-light rounded-pill text-success">No Issues</span>
              </div>
            </div>
          </div>
        </div>
      <% elsif group_constrained?(@feature) %>
        <%# Route paid to backup provider %>
        <div class="container text-center">
          <div class="row align-items-end">
            <div class="col flex-column align-items-center align-content-end justify-content-end">
              <div class="bg-dark rounded-pill d-inline-flex align-items-center align-content-center justify-content-center text-white gap-1 ps-2 pe-1 py-1">
                <%= icon 'person-fill', 'bi-medium' %>
                <small>Free</small>
                <span class="badge bg-light rounded-pill text-dark"><%= total_users - paid %></span>
              </div>
              <div class="w-100"><%= icon 'arrow-down-circle-fill', 'bi-medium text-secondary my-3' %></div>
              <div class="text-bg-warning rounded-pill d-inline-flex align-items-center align-content-center justify-content-center gap-2 px-4 py-3">
                <%= icon 'hdd-rack', 'bi-medium' %>
                <small>Primary</small>
                <span class="badge bg-light rounded-pill text-dark">Degraded</span>
              </div>
            </div>
            <div class="col flex-column align-items-center">
              <div class="bg-dark rounded-pill d-inline-flex align-items-center align-content-center justify-content-center text-white gap-1 ps-2 pe-1 py-1">
                <%= icon 'person-fill-check', 'bi-medium' %>
                <small>Paid</small>
                <span class="badge bg-light rounded-pill text-dark"><%= paid %></span>
              </div>
              <div class="w-100"><%= icon 'arrow-down-circle-fill', 'bi-medium text-secondary my-3' %></div>
              <div class="bg-success rounded-pill d-inline-flex align-items-center align-content-center justify-content-center text-white gap-2 px-4 py-3">
                <%= icon 'hdd-rack-fill', 'bi-medium' %>
                <small>Backup</small>
                <span class="badge bg-light rounded-pill text-success">No Issues</span>
              </div>
            </div>
          </div>
        </div>
      <% elsif percentage_of_time?(@feature) %>
        <%# Split traffic evenly between providers %>
        <div class="container text-center">
          <div class="row align-items-end">
            <div class="col flex-column align-items-center align-content-end justify-content-end">
              <div class="bg-dark rounded-pill d-inline-flex align-items-center align-content-center justify-content-center text-white gap-1 ps-2 pe-1 py-1">
                <%= icon 'people-fill', 'bi-medium' %>
                <small>All</small>
                <span class="badge bg-light rounded-pill text-dark"><%= total_users %></span>
              </div>
              <div class="w-100"><%= icon 'arrow-down-circle-fill', 'bi-medium text-secondary my-3' %></div>
            </div>
          </div>
          <div class="row">
            <div class="col d-flex align-items-center align-content-center justify-content-around gap-1 bg-success-subtle p-4 rounded-pill">
              <div class="bg-success rounded-pill d-inline-flex align-items-center align-content-center justify-content-center text-white gap-2 px-4 py-3">
                <%= icon 'hdd-rack-fill', 'bi-medium' %>
                <small>Primary</small>
                <span class="badge bg-light rounded-pill text-success">50%</span>
              </div>
              <div class="bg-success rounded-pill d-inline-flex align-items-center align-content-center justify-content-center text-white gap-2 px-4 py-3">
                <%= icon 'hdd-rack', 'bi-medium' %>
                <small>Backup</small>
                <span class="badge bg-light rounded-pill text-success">50%</span>
              </div>
            </div>
          </div>
        </div>
      <% elsif @feature.off? %>
        <div class="container text-center">
          <div class="row align-items-end">
            <div class="col flex-column align-items-center align-content-end justify-content-end">
              <div class="bg-dark rounded-pill d-inline-flex align-items-center align-content-center justify-content-center text-white gap-1 ps-2 pe-1 py-1">
                <%= icon 'people-fill', 'bi-medium' %>
                <small>All</small>
                <span class="badge bg-light rounded-pill text-dark"><%= total_users %></span>
              </div>

              <div class="w-100"><%= icon 'arrow-down-circle-fill', 'bi-medium text-secondary my-3' %></div>

              <div class="bg-success rounded-pill d-inline-flex align-items-center align-content-center justify-content-center text-white gap-2 px-4 py-3">
                <%= icon 'hdd-rack-fill', 'bi-medium' %>
                <small>Primary</small>
                <span class="badge bg-light rounded-pill text-success">No Issues</span>
              </div>
            </div>
            <div class="col flex-column align-items-center">
              <div class="bg-secondary-subtle rounded-pill d-inline-flex align-items-center align-content-center justify-content-center text-secondary gap-2 px-4 py-3">
                <%= icon 'hdd-rack', 'bi-medium' %>
                <small>Backup</small>
                <span class="badge bg-light rounded-pill text-body-tertiary">Standby</span>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <ul>
          <li>group names: <%= @feature.groups_value %></li>
          <li>feature gates: <%= @feature.enabled_gate_names %></li>
          <li>off? <%= @feature.off? %></li>
          <li>conditional? <%= @feature.conditional? %></li>
          <li>on? <%= @feature.on? %></li>
          <li>binary? <%= binary?(@feature) %></li>
          <li>actor_constrained? <%= actor_constrained?(@feature) %></li>
          <li>group_constrained? <%= group_constrained?(@feature) %></li>
          <li>percentage_of_time? <%= percentage_of_time?(@feature) %></li>
          <li>percentage_of_actors? <%= percentage_of_actors?(@feature) %></li>
        </ul>
      <% end %>
    </div>
    <div class="card-body bg-light p-0">
      <details class="m-0 p-0">
        <summary class="text-secondary text-center border-top p-2"><small>Inspect Flag State & Code Samples</small></summary>
        <ul class="list-group list-group-flush pt-0 border-top mx-3 px-0">
          <% [
            [
              "100% to primary provider?",
              binary?(@feature) && !@feature.enabled?,
              "@feature.off?"
            ],
            [
              "100% to backup provider?",
              binary?(@feature) && @feature.enabled? ,
              "@feature.on?"
            ],
            [
              "Balance traffic across providers?",
              percentage_of_time?(@feature),
              "@feature.percentage_of_time_value.positive? && @feature.percentage_of_time_value < 100"
            ],
            [
              "Route paying customers to backup provider?",
              group_constrained?(@feature),
              "@feature.groups_value.include?('paid')"
            ],
          ].each do |scenario| %>
            <%= status_item(*scenario) %>
          <% end %>
        </ul>
      </details>
    </div>
    <%= controls "Manage Backup Provider" do %>
      <% if @feature.on? || @feature.conditional? %>
        <%= toggle(
          label: 'Switch Entirely to Primary Provider',
          form_target: disable_path(feature: @example.flag),
          form_method: :delete,
          ruby: "Flipper.disable(:#{@example.flag})",
          cli: "flipper disable #{@example.flag}"
          ) %>
      <% end %>
      <% if @feature.off? || @feature.conditional? %>
        <%= toggle(
          label: 'Switch Entirely to Backup Provider',
          form_target: enable_path(feature: @example.flag),
          form_method: :post,
          ruby: "Flipper.enable(:#{@example.flag})",
          cli: "flipper enable #{@example.flag}"
          ) %>
      <% end %>
      <% if @feature.groups_value.include?('paid') %>
        <%= toggle(
          label: "Switch VIP's to Primary Provider",
          form_target: disable_path(feature: @example.flag, group: :paid),
          form_method: :delete,
          ruby: "Flipper.disable_group(:#{@example.flag}, :paid)",
          cli: "flipper disable #{@example.flag} --group paid"
          ) %>
      <% elsif @feature.off? %>
        <%= toggle(
          label: "Switch VIP's to Backup Provider",
          form_target: enable_path(feature: @example.flag, group: :paid),
          form_method: :post,
          ruby: "Flipper.enable_group(:#{@example.flag}, :paid)",
          cli: "flipper enable #{@example.flag} --group paid"
          ) %>
        <%= toggle(
          label: "Balance Providers",
          form_target: enable_path(feature: @example.flag, time: 50),
          form_method: :post,
          ruby: "Flipper.enable_percentage_of_time(:#{@example.flag}, 50)",
          cli: "flipper enable #{@example.flag} --percentage-of-time 50"
          ) %>
      <% end %>
    <% end %>
  </div>

  <p class="mt-4"><strong><mark>Important:</mark></strong> Behind the scenes, we've already registered and defined the <code>:paid</code> group in <code>config/initializers/flipper.rb</code>:</p>

  <pre class="border rounded rounded-4 p-3 bg-body-tertiary"><code><strong class="text-success">Flipper.register(:paid)</strong> do |actor, context|
  actor.respond_to?(:paid?) && actor.paid?
end</code></pre>
<% end %>

<% content_for :footer do %>
  <%= page_footer(__FILE__) %>
<% end %>

app/views/example/_circuit_breakers.html.erb
<%= uses([
  ["stopwatch", "<strong>Respond quickly to degraded performance or downtime</strong> by being able to instantly enable or disable a feature without needing to re-deploy."],
  ["person-raised-hand", "<strong>Reduce support requests</strong> by proactively informing customers about issues the team is already investigating by disabling only features with degraded performance."],
  ["emoji-heart-eyes", "<strong>Provide a better user experience</strong> using detailed explanations or well-designed interface adjustments instead of generic error pages."],
]) %>


<% content_for :aside do %>
  <div class="card border-5 border-dark rounded-4">
    <div class="card-header p-3 pb-2 border-bottom">
      <%= flag_status(@example.flag) %>
    </div>
    <div class="card-body p-5">
      <% if @feature.enabled?(current_user) %>
        <form class="d-flex gap-2 m-2">
          <input type="search" placeholder="Search" class="form-control">
          <input type="submit" value="Search" class="btn btn-primary">
        </form>
      <% else %>
        <div data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Search is temporarily disabled while the team investigates performance issues.">
          <form class="d-flex gap-2 m-2">
            <input type="search" placeholder="Search" class="form-control" disabled>
            <input type="submit" value="Search" class="btn btn-primary" disabled>
          </form>
        </div>
      <% end %>
    </div>
    <div class="card-body bg-light p-0">
      <details class="m-0 p-0">
        <summary class="text-secondary text-center border-top p-2"><small>Inspect Flag State & Code Samples</small></summary>
        <ul class="list-group list-group-flush pt-0 border-top mx-3 px-0">
          <% [
            ['Fully enabled for everyone?', Flipper.enabled?(@example.flag), "Flipper.enabled?(:#{@example.flag})"],
            ['Enabled for the current user?', Flipper.enabled?(@example.flag, current_user), "Flipper.enabled?(:#{@example.flag}, current_user)"],
          ].each do |scenario| %>
            <%= status_item(*scenario) %>
          <% end %>
        </ul>
      </details>
    </div>
    <%= controls "Update Search" do %>
      <div class="w-100">
        <% if @feature.on? %>
          <%= toggle(
            label: 'Disable for Everyone',
            form_target: disable_path(feature: @example.flag),
            form_method: :delete,
            ruby: "Flipper.disable(:#{@example.flag})",
            cli: "flipper disable #{@example.flag}"
            ) %>
        <% else %>
          <%= toggle(
            label: 'Enable for Everyone',
            form_target: enable_path(feature: @example.flag),
            form_method: :post,
            ruby: "Flipper.enable(:#{@example.flag})",
            cli: "flipper enable #{@example.flag}"
            ) %>
        <% end %>
      </div>
      <div class="w-100 border-top border-secondary border-opacity-50">
        <% if @feature.enabled?(current_user) %>
          <%= toggle(
            label: 'Disable for Just You',
            form_target: disable_path(feature: @example.flag, user: true),
            form_method: :delete,
            ruby: "Flipper.disable(:#{@example.flag}, current_user)",
            cli: "flipper disable #{@example.flag} --actor #{current_user.flipper_id}"
            ) %>
        <% else %>
          <%= toggle(
            label: 'Enable for Just You',
            form_target: enable_path(feature: @example.flag, user: true),
            form_method: :post,
            ruby: "Flipper.enable(:#{@example.flag}, current_user)",
            cli: "flipper enable #{@example.flag} --actor #{current_user.flipper_id}"
            ) %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

<% content_for :footer do %>
  <%= page_footer(__FILE__) %>
<% end %>

app/views/example/_managing_external_tools.html.erb
<%= uses([
  ["bar-chart-fill", "<strong>Disable analytics in development</strong> while making it easy for developers to enable when necessary so development and testing work don't skew the analytics."],
  ["search", "<strong>Selectively enable/disable troubleshooting tools</strong> so developers can turn the tools on and off in production without change code or re-deploying."],
  ["chat-heart-fill", "<strong>Suppress customer-centric widgets</strong> for internal team members that don't need them so everything runs faster."],
]) %>

<hr class="my-4">

<p>Let's considerer a tool like <a href="https://github.com/MiniProfiler/rack-mini-profiler"><code>rack-mini-profiler</code></a>. Would you ever want it on in production all of the time for each and every user? Probably not. You might however want to enable it in production for individual team members to troubleshoot a performance issue hasn't been reproducible in development.</p>

<p>Alternatively, would you want it on for everyone by default in development? That may be less of an issue, but for some teammates, the widget may get in the way of doing design or other front-end work.</p>

<p>Much of this could be handled with checks like <code>Rails.env.production?</code> or <code>Rails.env.local?</code>, but that can only easily consider the environment. And changing that logic would require re-deploying and the waiting that goes along with it.</p>

<p>With Feature Flags, everyone on the team can have more granualar control over which tools and widgets they want to see in which environment, and they can turn them on or off any time they want without any changes to the code itself—let alone waiting to deploy new code.</p>

<% content_for :aside do %>
  <div class="card border-5 border-dark rounded-4">
    <div class="card-header p-3 pb-2 border-bottom">
      <%= flag_status(@example.flag) %>
    </div>
    <div class="card-body p-5">
      <div class="d-flex align-items-center align-content-center justify-content-start gap-2">
        <% if @feature.enabled?(current_user) %>
          <%= icon 'check-circle-fill', 'bi-medium text-success' %>
          <span>Profiling was <ins>enabled</ins> for this request, but only for the current user.</span>
        <% else %>
          <%= icon 'x-circle-fill', 'bi-medium text-danger' %>
          Profiling was <del>disabled</del> for this request.
        <% end %>
      </div>
    </div>
    <div class="card-body bg-light p-0">
      <details class="m-0 p-0">
        <summary class="text-secondary text-center border-top p-2"><small>Inspect Flag State & Code Samples</small></summary>
        <ul class="list-group list-group-flush pt-0 border-top mx-3 px-0">
          <% [
              ['Fully enabled for everyone?', @feature.on?, "Flipper.enabled?(:#{@example.flag})"],
              ['Enabled for the current user?', @feature.enabled?(current_user), "Flipper.enabled?(:#{@example.flag}, current_user)"],
            ].each do |scenario| %>
            <%= status_item(*scenario) %>
          <% end %>
        </ul>
      </details>
    </div>
    <%= controls "Update Search" do %>
      <div class="w-100">
        <% if Flipper.enabled?(@example.flag, current_user) %>
          <%= toggle(
            label: 'Disable Profiler for Just You',
            form_target: disable_path(feature: @example.flag, user: true),
            form_method: :delete,
            ruby: "Flipper.disable(:#{@example.flag}, current_user)",
            cli: "flipper disable #{@example.flag} --actor #{current_user.flipper_id}"
            ) %>
        <% else %>
          <%= toggle(
            label: 'Enable Profiler for Just You',
            form_target: enable_path(feature: @example.flag, user: true),
            form_method: :post,
            ruby: "Flipper.enable(:#{@example.flag}, current_user)",
            cli: "flipper enable #{@example.flag} --actor #{current_user.flipper_id}"
            ) %>
        <% end %>
      </div>
    <% end %>
  </div>

  <p class="mt-5">To power this, we could add some code to our <code>ApplicationController</code>:</p>

<pre class="border rounded rounded-4 p-3 bg-body-tertiary"><code>class ApplicationController < ActionController::Base
  before_action :setup_rack_mini_profiler

  private

  def setup_rack_mini_profiler
    if <strong class="text-success">Flipper.enabled?(:profiler, current_user)</strong>
      Rack::MiniProfiler.authorize_request
    end
  end
end</code></pre>

<% end %>

<% content_for :footer do %>
  <%= page_footer(__FILE__) %>
<% end %>

app/views/example/index.html.erb
<% content_for :breadcrumbs do %>
<ol class="breadcrumb breadcrumb-chevron mb-0">
  <li class="breadcrumb-item"><strong class="badge bg-secondary rounded rounded-pill m-0 fs-6">Examples</strong></li>
  <li class="breadcrumb-item active" aria-current="page">All</li>
</ol>
<% end %>

<h1>Feature Flag Examples</h1>
<p>Feature flags are capable of so much more than simply enabling or disabling features. They can help turn off analytics in development or enable troubleshooting tools in production for a single developer or group of developers. They can help temporarily disable features that have issues or provide a way to instantly switch to a backup provider if a primary goes offline.</p>

<p>We've created examples of some of our favorite use cases here so you can try them out and see how to apply them to your own application.</p>


<% content_for :aside do %>
  <div class="list-group rounded-4">
    <% Example.list.each do |example| %>
      <a href="<%= example_path(slug: example.slug) %>" class="list-group-item list-group-item-action d-flex gap-3 py-3 align-items-start" aria-current="true">
        <%= icon example.icon, "bi-large text-info" %>
        <div class="d-flex gap-2 w-100 justify-content-between">
          <div>
            <h6 class="mb-0 fw-bold"><%= example.title %></h6>
            <p class="mb-0 opacity-75"><%= example.desc %></p>
          </div>
          <div class="text-wrap text-end">
            <% example.tags.each do |tag| %>
              <% label, style = tag %>
              <small class="badge fw-light rounded-pill text-bg-<%= style %>"><%= label %></small>
            <% end %>
          </div>
        </div>
      </a>
    <% end %>
  </div>
<% end %>


<% content_for :footer do %>
  <%= page_footer(__FILE__) %>
<% end %>

app/views/example/show.html.erb
<% content_for :breadcrumbs do %>
<ol class="breadcrumb breadcrumb-chevron mb-0">
  <li class="breadcrumb-item"><strong class="badge bg-primary bg-opacity-75 rounded rounded-pill m-0 fs-6">Examples</strong></li>
  <li class="breadcrumb-item"><a href="<%= examples_path %>">All</a></li>
  <li class="breadcrumb-item active" aria-current="page"><%= @example.title %></li>
</ol>
<% end %>


<h1><%= @example.title %></h1>
<p class="lead border-bottom pb-3 mb-3"><%= @example.desc %></p>


<%= render @example %>