config/routes.rb
Rails.application.routes.draw do
  root 'home#show'

  patch "profile", to: "profile#update", as: :profile

  # Feature flipping
  post   'features/enable/:feature',  to: "features#create",  as: :enable
  delete 'features/disable/:feature', to: "features#destroy", as: :disable

  # The demo pages which use feature toggles to unlock the next step...
  post 'demo/reset'
  get 'demo/start'
  get 'demo/actor'
  get 'demo/group', as: :coffee_beta
  get 'demo/percentage'

  # The example pages
  get 'example/index', as: :examples
  get 'example/:slug', to: "example#show", as: :example

  get "cli", to: "cli#show", as: :cli
  post "cli", to: "cli#execute"

  get 'connect/:token', to: "cloud#connect", as: :cloud_connect

  # The Flipper UI gem interface.
  #
  # IMPORTANT: In production, you'd want to limit access to this, or anybody would be able to
  #   control your feature toggles.
  #
  # More info on Flipper UI Security & Authorization:
  #   https://www.flippercloud.io/docs/ui#security
  mount Flipper::UI.app(Flipper) => '/flipper'
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  def reset
    Flipper.features.each(&:clear)
    reset_session

    flash[:notice] = "The demo is reset and ready to go through again."
    redirect_to demo_start_path
  end

  def start
  end

  def actor
  end

  def group
    @water_drinker = User.water.first
    @tea_drinker = User.tea.first
    @coffee_drinker = User.coffee.first
  end

  def percentage
    @current_percentage = session[:percentage]&.to_i || 0
  end

  private

  def required_feature
    "demo_#{action_name}".to_sym
  end
end

app/helpers/demo_helper.rb
module DemoHelper
  def controls(title)
    render 'shared/controls', title: do
      yield
    end
  end

  def flag_status(feature)
    feature = Flipper.feature(feature) if feature.is_a?(Symbol)
    render 'shared/flag_status', feature: do
      yield
    end
  end

  def status_item(label, condition, code = nil)
    render 'shared/status_item', label: , condition: , code:
  end

  def uses(examples)
    render 'shared/uses', examples: examples
  end

  def toggle(label:, form_target:, form_method: :post, ruby:, cli:)
    style = case form_method
            when :post then :success
            when :delete then :danger
            else :primary
            end
    render 'shared/toggle', label:, style:, form_target:, form_method:, ruby:, cli:
  end

  def next_button(label, target)
    render 'shared/next_button', label:, target:
  end
end

app/views/demo/actor.html.erb
<% content_for :breadcrumbs do %>
<ol class="breadcrumb breadcrumb-chevron mb-0">
  <li class="breadcrumb-item"><strong class="badge bg-secondary rounded rounded-pill m-0 fs-6">Demo</strong></li>
  <li class="breadcrumb-item"><a href="<%= demo_start_path %>">Basic Flags</a></li>
  <li class="breadcrumb-item active" aria-current="page">Flags & Actors</li>
</ol>
<% end %>

<% if !Flipper.enabled?(:demo_actor, current_user) %>
  <h1>Actor-based Feature Flipping</h1>
  <p>You can also toggle a feature on or off for <strong>a specific user</strong>. You can enable access for users several ways, but for this example, we'll focus on enabling a feature for a specific user rather than a group that includes that user.</p>

  <p>Previously, we enabled the demo for all users. While that's the simplest case and very handy when a feature is completely ready, you'll occasionally want to enable a feature for a single individual like yourself or a teammate. So let's see how that works.</p>

  <p>We've named this feature flag <code>:demo_actor</code> because it only enables the feature for a single user. In this case, we'll use <code>current_user</code>, but in practice, you could use any instance of a User, Organization, Team, or any "actor" from your system as long as the instance responds to <code>flipper_id</code>.</p>

  <p><strong><mark>Important:</mark></strong> In order to <a href="https://www.flippercloud.io/docs/features#enablement-actor">enable access for individual users, accounts, or any other actor</a> the model must respond to a <code>flipper_id</code> method that returns a unique identifier.</p>
<% end %>

<% if Flipper.enabled?(:demo_actor, current_user) %>
  <h1>That's It for Actors</h1>
  <p>That's all for enabling features for individual actors. Next we'll look at how you can enable features for groups of actors by registering groups and specifying the conditions that indicate an actor is in that group.</p>

  <%= next_button "Toggle Features for Groups", coffee_beta_path %>
<% end %>

<% content_for :aside do %>
  <div class="card border-5 border-dark rounded-4">
    <div class="card-header p-3 pb-2 border-bottom">
      <%= flag_status(:demo_actor) %>
      <ul class="list-group list-group-flush pt-0 border-top mt-2">
        <% [
          ['Fully enabled for everyone?', Flipper.enabled?(:demo_actor), 'Flipper.enabled?(:demo_actor)'],
          ['Enabled for the current user?', Flipper.enabled?(:demo_actor, current_user), "Flipper.enabled?(:demo_actor, current_user)"],
        ].each do |scenario| %>
          <%= status_item(*scenario) %>
        <% end %>
      </ul>
    </div>
    <div class="card-body p-5">
      <% if Flipper.enabled?(:demo_actor) %>
        <p class="m-0">The <code>:demo_actor</code> feature is <ins>enabled</ins> for everyone.</p>
      <% else %>
        <p class="m-0">The <code>:demo_actor</code> feature is <del>disabled</del> for anyone that doesn't have special authorization.</p>
      <% end %>

      <hr>

      <% if Flipper.enabled?(:demo_actor) %>
        <p class="m-0">The <code>:demo_actor</code> feature is <em>implicitly</em> <ins>enabled</ins> for you since it's enabled for everyone.</p>
      <% elsif Flipper.enabled?(:demo_actor, current_user) %>
        <p class="m-0">The <code>:demo_actor</code> feature is <em>explicitly</em> <ins>enabled</ins> for you.</p>
      <% elsif !Flipper.enabled?(:demo_actor, current_user) %>
        <p class="m-0">The <code>:demo_actor</code> feature is <em>implicitly</em> <del>disabled</del> for you as well.</p>
      <% end %>
    </div>
    <%= controls('Toggling an Flag for an Actor') do %>
      <div class="w-100">
        <% if Flipper.enabled?(:demo_actor) %>
          <%= toggle(
            label: 'Disable for Everyone',
            form_target: disable_path(feature: :demo_actor),
            form_method: :delete,
            ruby: "Flipper.disable(:#{:demo_actor})",
            cli: "flipper disable #{:demo_actor}"
            ) %>
        <% else %>
          <%= toggle(
            label: 'Enable for Everyone',
            form_target: enable_path(feature: :demo_actor),
            form_method: :post,
            ruby: "Flipper.enable(:#{:demo_actor})",
            cli: "flipper enable #{:demo_actor}"
            ) %>
        <% end %>
      </div>
      <% if !Flipper.enabled?(:demo_actor) %>
      <div class="w-100 border-top border-secondary border-opacity-50">
        <% if Flipper.enabled?(:demo_actor, current_user) %>
          <%= toggle(
            label: 'Disable for Just You',
            form_target: disable_path(feature: :demo_actor, user: true),
            form_method: :delete,
            ruby: "Flipper.disable(:#{:demo_actor}, current_user)",
            cli: "flipper disable #{:demo_actor} --actor #{current_user.flipper_id}"
            ) %>
        <% else %>
          <%= toggle(
            label: 'Enable for Just You',
            form_target: enable_path(feature: :demo_actor, user: true),
            form_method: :post,
            ruby: "Flipper.enable(:#{:demo_actor}, current_user)",
            cli: "flipper enable #{:demo_actor} --actor #{current_user.flipper_id}"
            ) %>
        <% end %>
      </div>
      <% end %>
    <% end %>
  </div>
<% end %>

<% content_for :footer do %>
  <%= page_footer(__FILE__) %>
<% end %>

app/views/demo/group.html.erb
<% content_for :breadcrumbs do %>
<ol class="breadcrumb breadcrumb-chevron mb-0">
  <li class="breadcrumb-item"><strong class="badge bg-secondary rounded rounded-pill m-0 fs-6">Demo</strong></li>
  <li class="breadcrumb-item"><a href="<%= demo_start_path %>">Basic Flags</a></li>
  <li class="breadcrumb-item"><a href="<%= demo_actor_path %>">Flags & Actors</a></li>
  <li class="breadcrumb-item active" aria-current="page">Flags & Groups</li>
</ol>
<% end %>


<% if Flipper.enabled?(:coffee_beta, @coffee_drinker) %>

  <% if Flipper.enabled?(:coffee_beta, current_user) %>
    <h1>Welcome to the club!</h1>
    <p>The <code>:coffee_beta</code> feature is <ins>enabled</ins> for you since you prefer coffee. Nice work! Next we'll look at how you can enable features for a percentage of users.</p>
    <%= next_button "Learn How Percentage Flags Work", demo_percentage_path %>
  <% else %>
    <h1>Your Beverage Preference</h1>
    <p>The <code>:coffee_beta</code> feature is <del>disabled</del> for you since you don't prefer coffee. Let's update your beverage preference so you'll be included in the coffee drinkers group and get access.</p>
  <% end %>

  <hr class="my-5">

  <p><strong><mark>Important:</mark></strong> Even if coffee's not your thing, the rest of the demo is only for coffee drinkers, and there's no penalty for lying.</p>

  <%= form_with model: current_user, method: :patch, url: profile_path do |f| %>
    <div class="list-group rounded-4 mb-2">
      <% %w[water tea coffee].each do |bev| %>
        <label class="list-group-item d-flex align-items-top align-content-center justify-content-between gap-2 p-3">
          <%= f.radio_button("beverage", bev, class: 'form-check-input flex-shrink-0', checked: current_user.beverage.to_s == bev) %>
          <div class="d-block w-100">
            <strong><%= bev.capitalize %></strong>
            <small class="d-block text-body-secondary">
              <%=
                if bev == 'coffee'
                  "You'll be included in the beta testing for coffee-related features!"
                else
                  "A great drink, but you won't be in the Coffee group and won't get early access to our new coffee-related features."
                end
              %>
            </small>
          </div>
          <div class="ms-4">
            <% if bev == 'water' %>
              <%= icon 'cup-straw', 'bi-large text-primary' %>
            <% elsif bev == 'tea' %>
              <%= icon 'cup', 'bi-large text-warning-emphasis' %>
            <% else %>
              <%= icon 'cup-hot', 'bi-large text-body-emphasis' %>
            <% end %>
          </div>
        </label>
      <% end %>
    </div>
    <%= f.submit "Save my Drink Preference", class: 'btn btn-primary w-100 rounded rounded-pill' %>
  <% end %>
<% else %>
  <h1>Group-based Feature Flipping</h1>
  <p>Let's see how  to <a href="https://www.flippercloud.io/docs/features#enablement-group">enable access for a group of users</a>. For that, we need to register the group and specify the conditions that determine whether a given actor is included in the group. Since our new feature would only be relevant for coffee drinkers, we'll only enable it for them.</p>

  <p>We've named this feature flag <code>coffee_beta</code>. We still pass <code>current_user</code> as the actor, but instead of having enabled the user directly, we'll enable the group and the current user would be enabled implicitly if they're a member of the coffee group.</p>

  <hr class="my-5">

  <p><strong><mark>Important:</mark></strong> Behind the scenes, we've already registered and defined the coffee drinker group in <code>config/initializers/flipper.rb</code>:</p>

  <pre class="border rounded rounded-4 p-3 bg-body-tertiary"><code><strong class="text-success">Flipper.register(:coffee_drinkers)</strong> do |actor, context|
  actor.respond_to?(:coffee?) && actor.coffee?
end</code></pre>
<% end %>


<% content_for :aside do %>
  <div class="card border-5 border-dark rounded-4">
    <div class="card-header p-3 pb-2 border-bottom">
      <%= flag_status(:coffee_beta) %>
      <ul class="list-group list-group-flush pt-0 border-top mt-2">
        <% [
          ['Fully enabled for everyone?', Flipper.enabled?(:coffee_beta), 'Flipper.enabled?(:coffee_beta)'],
          ['Enabled for the current user?', Flipper.enabled?(:coffee_beta, current_user), "Flipper.enabled?(:coffee_beta, current_user)"],
        ].each do |scenario| %>
          <%= status_item(*scenario) %>
        <% end %>
      </ul>
    </div>
    <div class="card-body p-5">
      <% if Flipper.enabled?(:coffee_beta) %>
        <p class="m-0">The <code>:coffee_beta</code> feature is <ins>enabled</ins> for everyone.</p>
      <% else %>
        <p class="m-0">The <code>:coffee_beta</code> feature is <del>disabled</del> for anyone that doesn't have special authorization.</p>
      <% end %>

      <hr>

      <% if Flipper.enabled?(:coffee_beta, @water_drinker) %>
        <p class="m-0">The <code>:coffee_beta</code> feature is <ins>enabled</ins> for water drinkers.</p>
      <% else %>
        <p class="m-0">The <code>:coffee_beta</code> feature is <del>disabled</del> for water drinkers.</p>
      <% end %>


      <% if Flipper.enabled?(:coffee_beta, @tea_drinker) %>
        <p class="m-0">The <code>:coffee_beta</code> feature is <ins>enabled</ins> for tea drinkers.</p>
      <% else %>
        <p class="m-0">The <code>:coffee_beta</code> feature is <del>disabled</del> for tea drinkers.</p>
      <% end %>

      <% if Flipper.enabled?(:coffee_beta, @coffee_drinker) %>
        <p class="m-0">The <code>:coffee_beta</code> feature is <ins>enabled</ins> for coffee drinkers.</p>
      <% else %>
        <p class="m-0">The <code>:coffee_beta</code> feature is <del>disabled</del> for coffee drinkers.</p>
      <% end %>
    </div>
    <%= controls('Toggling an Flag for an Actor') do %>
      <div class="w-100">
        <% if Flipper.enabled?(:coffee_beta, @coffee_drinker) %>
          <%= toggle(
            label: 'Disable for Coffee Drinkers',
            form_target: disable_path(feature: :coffee_beta, group: :coffee_drinkers),
            form_method: :delete,
            ruby: 'Flipper.disable_group(:coffee_beta, :coffee_drinkers)',
            cli: 'flipper disable coffee_beta --group=coffee_drinkers'
            ) %>
        <% else %>
          <%= toggle(
            label: 'Enable for Coffee Drinkers',
            form_target: enable_path(feature: :coffee_beta, group: :coffee_drinkers),
            form_method: :post,
            ruby: 'Flipper.enable_group(:coffee_beta, :coffee_drinkers)',
            cli: 'flipper enable coffee_beta --group=coffee_drinkers'
            ) %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

<% content_for :footer do %>
  <%= page_footer(__FILE__) %>
<% end %>

app/views/demo/percentage.html.erb
<% content_for :breadcrumbs do %>
<ol class="breadcrumb breadcrumb-chevron mb-0">
  <li class="breadcrumb-item"><strong class="badge bg-secondary rounded rounded-pill m-0 fs-6">Demo</strong></li>
  <li class="breadcrumb-item"><a href="<%= demo_start_path %>">Basic Flags</a></li>
  <li class="breadcrumb-item"><a href="<%= demo_actor_path %>">Flags & Actors</a></li>
  <li class="breadcrumb-item"><a href="<%= coffee_beta_path %>">Flags & Groups</a></li>
  <li class="breadcrumb-item active" aria-current="page">Flags & Percentages</li>
</ol>
<% end %>

<%
  enabled_water_drinkers = 0
  enabled_tea_drinkers = 0
  enabled_coffee_drinkers = 0

  User.all.each do |user|
    next unless Flipper.enabled?(:slow_roll, user)

    if user.water?
      enabled_water_drinkers += 1
    elsif user.tea?
      enabled_tea_drinkers += 1
    elsif user.coffee?
      enabled_coffee_drinkers += 1
    end
  end
%>

<% if @current_percentage.zero? %>
  <h1>Percentage-based Feature Flipping</h1>
  <p>Let's explore toggling by using percentages where we can enable a feature for a <a href="https://www.flippercloud.io/docs/features#enablement-percentage-of-actors">percentage of actors</a> or for a <a href="https://www.flippercloud.io/docs/features#enablement-percentage-of-time">percentage of time</a>. As we're increasingly confident there aren't any surprise bugs or performance issues, we can gradually increase the percentage.</p>

  <p>We've named this feature flag <code>:slow_roll</code> since we'll slowly roll it out to more users. We'll increase our percentage gradually in increments of 25% and see how it four different user accounts, including yours, are affected.</p>

  <p>This is great for refactoring a significant portion of code so you can keep the legacy portion in place in parallel with the new code that's set to replace it, and you can slowly send more traffic down the new code path until you're confident it's generating the same results as the original.</p>

<% elsif @current_percentage.positive? && @current_percentage < 100 %>
  <h1>Time for another increase!</h1>
  <p><strong>Currently enabled for approximately <%= @current_percentage %>% of actors</strong>. This won't ever be an exact match for the percentage of enabled users due to the variables involved. The more total actors in the system, the closer this number will be to a precise percentage of overall users.</p>

<% elsif @current_percentage >= 100 %>
  <h1>Finished!</h1>
  <p>You've covered the basics of feature toggling, but we've glossed over some details. While you've been toggling features directly in the demo up until now, that's not really ideal. And that's where <a href="https://www.flippercloud.io/dashboard">Flipper Cloud</a> comes in.</p>

  <div class="d-flex gap-3">
    <%= button_to "Restart the Demo", demo_reset_path, method: :post, class: 'btn btn-primary btn-lg rounded rounded-pill' %>
    <%= button_to "Visit Your Flipper Cloud Account", 'https://flippercloud.io', method: :get, class: 'btn btn-outline-primary btn-lg rounded rounded-pill' %>
  </div>
<% end %>

<% content_for :aside do %>
  <div class="card border-5 border-dark rounded-4">
    <div class="card-header p-3 pb-2 border-bottom">
      <%= flag_status(:slow_roll) %>
      <ul class="list-group list-group-flush pt-0 border-top mt-2">
        <% [
          ['Fully enabled for everyone?', Flipper.enabled?(:slow_roll), 'Flipper.enabled?(:slow_roll)'],
          ['Enabled for the current user?', Flipper.enabled?(:slow_roll, current_user), "Flipper.enabled?(:slow_roll, current_user)"],
        ].each do |scenario| %>
          <%= status_item(*scenario) %>
        <% end %>
      </ul>
    </div>
    <div class="card-body p-5">

      <% if Flipper.enabled?(:slow_roll) %>
        <p class="m-0">The <code>:slow_roll</code> feature is <ins>enabled</ins> for everyone.</p>
      <% else %>
        <p class="m-0">The <code>:slow_roll</code> feature is <del>disabled</del> for those without special permission.</p>
      <% end %>

      <% if Flipper.enabled?(:slow_roll, current_user) %>
        <p class="m-0">The <code>:slow_roll</code> feature is <ins>enabled</ins> for you.</p>
      <% else %>
        <p class="m-0">The <code>:slow_roll</code> feature is <del>disabled</del> for you.</p>
      <% end %>

      <hr>

      <p class="m-0">The <code>:slow_roll</code> feature is <ins>enabled</ins> for
        <%= pluralize(enabled_water_drinkers, 'water drinker') %>
        <small class="badge text-bg-light border rounded-pill">~<%= number_to_percentage((enabled_water_drinkers * 100) / (User.water.any? ? User.water.count : 0), precision: 0) %></small></p>

      <p class="m-0">The <code>:slow_roll</code> feature is <ins>enabled</ins> for
        <%= pluralize(enabled_tea_drinkers, 'tea drinker') %>
        <small class="badge text-bg-light border rounded-pill">~<%= number_to_percentage((enabled_tea_drinkers * 100) / (User.water.any? ? User.water.count : 0), precision: 0) %></small></p>

      <p class="m-0">The <code>:slow_roll</code> feature is <ins>enabled</ins> for
        <%= pluralize(enabled_coffee_drinkers, 'coffee drinker') %>
        <small class="badge text-bg-light border rounded-pill">~<%= number_to_percentage((enabled_coffee_drinkers * 100) / (User.water.any? ? User.water.count : 0), precision: 0) %></small></p>

    </div>
    <%= controls('Toggling an Flag for an Actor') do %>
        <% if @current_percentage < 100 %>
          <div class="w-100">
            <%= toggle(
              label: 'Increase by 25%',
              form_target: enable_path(feature: :slow_roll, percentage: @current_percentage + 25),
              form_method: :post,
              ruby: "Flipper.enable_percentage_of_actors(:slow_roll, #{ @current_percentage + 25 })",
              cli: "flipper enable slow_roll --percentage-of-actors=#{ @current_percentage + 25 }"
              ) %>
          </div>
        <% end %>

        <% if @current_percentage > 0 %>
          <% if @current_percentage < 100 %>
            <div class="w-100 border-top border-secondary border-opacity-50">
          <% else %>
            <div class="w-100">
          <% end %>
            <%= toggle(
              label: 'Disable (Back to 0%)',
              form_target: disable_path(feature: :slow_roll, percentage: 0),
              form_method: :delete,
              ruby: 'Flipper.disable_percentage_of_actors(:slow_roll)',
              cli: 'flipper disable slow_roll --percentage-of-actors=0'
              ) %>
          </div>
        <% end %>
    <% end %>
  </div>
<% end %>

<% content_for :footer do %>
  <%= page_footer(__FILE__) %>
<% end %>

app/views/demo/start.html.erb
<% content_for :breadcrumbs do %>
<ol class="breadcrumb breadcrumb-chevron mb-0">
  <li class="breadcrumb-item"><strong class="badge bg-secondary rounded rounded-pill m-0 fs-6">Demo</strong></li>
  <li class="breadcrumb-item active" aria-current="page">Basic Flags</li>
</ol>
<% end %>

<% if !Flipper.enabled?(:demo) %>
  <h1>Fully Enable a Feature Flag</h1>
  <p><mark>You can toggle any feature without re-deploying, and all reads of feature flag values are always performed entirely local to your application to avoid roundtrip network requests.</mark> You can think of this as <a href="https://www.flippercloud.io/docs/features#enablement-boolean">boolean feature flipping</a> where it's either true or false for everyone.</p>
  <p>In this example, the Demo is behind a flag named <code>demo</code>. To enable (or disable) it, you can use the Flipper API, Flipper UI, or Flipper Cloud. In most cases, you wouldn't let folks toggle features for themselves like this, but it can be handy for letting them opt-in to test out new features ahead of a public release.</p>
<% else %>
  <h1>Nice flag toggling!</h1>
  <p>The <code>:demo</code> flag is enabled, and you're ready to take Flipper for a spin and enable features on a more specific basis now! Our first example focuses on enabling features for a specific user—you!</p>

  <%= next_button 'Toggle Features for Individual Actors', demo_actor_path %>
<% end %>



<% content_for :aside do %>
  <div class="card border-5 border-dark rounded-4">
    <div class="card-header p-3 pb-2 border-bottom">
      <%= flag_status(:demo) %>
      <ul class="list-group list-group-flush pt-0 border-top mt-2">
        <% [
          ['Fully enabled for everyone?', Flipper.enabled?(:demo), 'Flipper.enabled?(:demo)'],
        ].each do |scenario| %>
          <%= status_item(*scenario) %>
        <% end %>
      </ul>
    </div>
    <div class="card-body p-5">
      <% if Flipper.enabled?(:demo) %>
        The <code>:demo</code> flag is <ins>enabled</ins>! You can toggle it off and back on again if you want&hellip;
      <% else %>
        The <code>:demo</code> flag is <del>disabled</del>. <span class="text-secondary">(Flipper features are disabled by default.)</span>
      <% end %>
    </div>
    <%= controls('Toggling an Individual Flag for Everyone') do %>
      <% if Flipper.enabled?(:demo) %>
        <%= toggle(
          label: 'Disable the Demo Feature Flag',
          form_target: disable_path(feature: :demo),
          form_method: :delete,
          ruby: 'Flipper.disable(:demo)',
          cli: 'flipper disable demo'
          ) %>
      <% else %>
        <%= toggle(
          label: 'Enable the Demo Feature Flag',
          form_target: enable_path(feature: :demo),
          form_method: :post,
          ruby: 'Flipper.enable(:demo)',
          cli: 'flipper enable demo'
        ) %>
      <% end %>
    <% end %>
  </div>
<% end %>


<% content_for :footer do %>
  <%= page_footer(__FILE__) %>
<% end %>