config/routes.rb
Rails.application.routes.draw do
  root 'home#show'

  patch "profile", to: "profile#update", as: :profile

  # Feature flipping
  post   'features/enable/:feature',  to: "features#create",  as: :enable
  delete 'features/disable/:feature', to: "features#destroy", as: :disable

  # The demo pages which use feature toggles to unlock the next step...
  post 'demo/reset'
  get 'demo/start'
  get 'demo/actor'
  get 'demo/group', as: :coffee_beta
  get 'demo/percentage'

  # The example pages
  get 'example/index', as: :examples
  get 'example/:slug', to: "example#show", as: :example

  get "cli", to: "cli#show", as: :cli
  post "cli", to: "cli#execute"

  get 'connect/:token', to: "cloud#connect", as: :cloud_connect

  # The Flipper UI gem interface.
  #
  # IMPORTANT: In production, you'd want to limit access to this, or anybody would be able to
  #   control your feature toggles.
  #
  # More info on Flipper UI Security & Authorization:
  #   https://www.flippercloud.io/docs/ui#security
  mount Flipper::UI.app(Flipper) => '/flipper'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/views/home/show.html.erb
<h1 class="display-1">Welcome!</h1>
<p class="lead">
  This is a minimal Rails app that you can browse and interact with to see how Flipper works—a kind of virtual playground.
</p>

<p>If there's something you like, <mark>the footer of every page provides a link to the source code so you can take a look at how we did it</mark> and even use it in your own Rails app! If there's something you don't like, you can tinker with it and change it to figure out how it works or how you could use it.</p>

<% content_for :aside do %>
  <div class="card rounded-4">
    <div class="card-body">
      <p class="my-0">Once you walk through the demo or browse the examples, this area will display information and controls for some Flipper controls. Normally, you'd use Flipper Cloud to control feature flags, but for demonstration purposes, we've brought those controls right here.</p>
    </div>
  </div>

  <div class="d-flex gap-3 my-4">
    <%= next_button "Start the Demo", demo_start_path %>
    <%= next_button "Browse Examples", examples_path %>
  </div>


<% end %>



<% content_for :footer do %>
  <%= page_footer(__FILE__) %>
<% end %>